-- Tabela de mapeamento PT-BR -> slug do free-exercise-db
CREATE TABLE IF NOT EXISTS public.exercise_image_map (
  exercise_name_pt text PRIMARY KEY,
  slug text NOT NULL,
  source text NOT NULL DEFAULT 'free-exercise-db',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.exercise_image_map ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone authenticated reads image map"
  ON public.exercise_image_map FOR SELECT
  TO authenticated
  USING (true);

INSERT INTO public.exercise_image_map (exercise_name_pt, slug) VALUES
  ('Crossover na Polia', 'Cable_Crossover'),
  ('Crucifixo Inclinado', 'Incline_Dumbbell_Flyes'),
  ('Crucifixo Reto', 'Dumbbell_Flyes'),
  ('Flexão de Braço', 'Pushups'),
  ('Flexão Diamante', 'Push-Ups_-_Close_Triceps_Position'),
  ('Flexão Inclinada', 'Incline_Push-Up'),
  ('Mergulho em Paralelas (Peito)', 'Dips_-_Chest_Version'),
  ('Pullover com Halter', 'Bent-Arm_Dumbbell_Pullover'),
  ('Supino com Pegada Fechada', 'Close-Grip_Barbell_Bench_Press'),
  ('Supino Declinado com Barra', 'Decline_Barbell_Bench_Press'),
  ('Supino Inclinado com Barra', 'Barbell_Incline_Bench_Press_-_Medium_Grip'),
  ('Supino Inclinado com Halteres', 'Incline_Dumbbell_Press'),
  ('Supino na Máquina', 'Machine_Bench_Press'),
  ('Supino Reto com Barra', 'Barbell_Bench_Press_-_Medium_Grip'),
  ('Supino Reto com Halteres', 'Dumbbell_Bench_Press'),
  ('Voador (Peck Deck)', 'Butterfly'),
  ('voador maquina', 'Butterfly'),
  ('Barra Fixa Pronada', 'Pullups'),
  ('Barra Fixa Supinada', 'Chin-Up'),
  ('Bom Dia (Good Morning)', 'Good_Morning'),
  ('Encolhimento com Barra', 'Barbell_Shrug'),
  ('Encolhimento com Halteres', 'Dumbbell_Shrug'),
  ('Face Pull', 'Face_Pull'),
  ('Hiperextensão Lombar', 'Hyperextensions_With_No_Hyperextension_Bench'),
  ('Levantamento Terra', 'Barbell_Deadlift'),
  ('Pulldown com Braços Estendidos', 'Straight-Arm_Pulldown'),
  ('puxada alta aberta', 'Wide-Grip_Lat_Pulldown'),
  ('Puxada Frontal na Polia', 'Full_Range-Of-Motion_Lat_Pulldown'),
  ('Puxada na Polia Pegada Fechada', 'Close-Grip_Front_Lat_Pulldown'),
  ('Remada Alta com Barra', 'Upright_Barbell_Row'),
  ('Remada Baixa na Polia', 'Seated_Cable_Rows'),
  ('Remada Cavalinho', 'T-Bar_Row_with_Handle'),
  ('Remada Curvada com Barra', 'Bent_Over_Barbell_Row'),
  ('Remada Serrote', 'One-Arm_Dumbbell_Row'),
  ('Remada Unilateral com Halter', 'One-Arm_Dumbbell_Row'),
  ('T-Bar Row', 'Lying_T-Bar_Row'),
  ('Crucifixo Inverso', 'Reverse_Flyes'),
  ('Desenvolvimento Arnold', 'Arnold_Dumbbell_Press'),
  ('Desenvolvimento com Barra', 'Barbell_Shoulder_Press'),
  ('Desenvolvimento com Halteres', 'Dumbbell_Shoulder_Press'),
  ('Desenvolvimento na Máquina', 'Machine_Shoulder_Military_Press'),
  ('Elevação Frontal', 'Front_Dumbbell_Raise'),
  ('Elevação Lateral', 'Side_Lateral_Raise'),
  ('Elevação Lateral na Polia', 'Cable_Seated_Lateral_Raise'),
  ('Handstand Push-up', 'Handstand_Push-Ups'),
  ('Pássaro na Máquina', 'Reverse_Machine_Flyes'),
  ('Push Press', 'Push_Press'),
  ('Remada Alta', 'Upright_Barbell_Row'),
  ('biceps martelo simultaneo', 'Hammer_Curls'),
  ('biceps scoth maquina', 'Machine_Preacher_Curls'),
  ('Chin-up', 'Chin-Up'),
  ('Rosca Alternada com Halteres', 'Dumbbell_Alternate_Bicep_Curl'),
  ('Rosca Concentrada', 'Concentration_Curls'),
  ('Rosca Direta com Barra', 'Barbell_Curl'),
  ('Rosca Inversa', 'Reverse_Barbell_Curl'),
  ('Rosca Martelo', 'Hammer_Curls'),
  ('Rosca na Polia', 'Standing_Biceps_Cable_Curl'),
  ('Rosca Scott', 'Preacher_Curl'),
  ('Rosca Spider', 'Spider_Curl'),
  ('Mergulho em Paralelas', 'Dips_-_Triceps_Version'),
  ('Mergulho no Banco', 'Bench_Dips'),
  ('Supino Pegada Fechada', 'Close-Grip_Barbell_Bench_Press'),
  ('Tríceps Coice', 'Tricep_Dumbbell_Kickback'),
  ('Tríceps Francês', 'Standing_Dumbbell_Triceps_Extension'),
  ('Tríceps na Máquina', 'Machine_Triceps_Extension'),
  ('Tríceps Pulley com Barra', 'Triceps_Pushdown'),
  ('Tríceps Pulley com Corda', 'Triceps_Pushdown_-_Rope_Attachment'),
  ('Tríceps Testa', 'Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head'),
  ('Tríceps Unilateral na Polia', 'Cable_One_Arm_Tricep_Extension'),
  ('Farmer Walk', 'Farmers_Walk'),
  ('Plate Pinch', 'Plate_Pinch'),
  ('Rosca de Punho', 'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench'),
  ('Rosca de Punho Inversa', 'Palms-Down_Wrist_Curl_Over_A_Bench'),
  ('adutora', 'Thigh_Adductor'),
  ('Afundo (Lunge)', 'Dumbbell_Lunges'),
  ('Agachamento Búlgaro', 'Split_Squat_with_Dumbbells'),
  ('Agachamento Frontal', 'Front_Barbell_Squat'),
  ('agachamento Globet squat com halteres', 'Goblet_Squat'),
  ('Agachamento Goblet', 'Goblet_Squat'),
  ('Agachamento Livre', 'Barbell_Squat'),
  ('Agachamento Sumô', 'Wide_Stance_Barbell_Squat'),
  ('Cadeira Extensora', 'Leg_Extensions'),
  ('Hack Squat', 'Hack_Squat'),
  ('Leg Press 45°', 'Leg_Press'),
  ('Passada (Walking Lunge)', 'Bodyweight_Walking_Lunge'),
  ('Pistol Squat', 'Smith_Machine_Pistol_Squat'),
  ('Step-up', 'Dumbbell_Step_Ups'),
  ('Cadeira Flexora', 'Seated_Leg_Curl'),
  ('flexão de joelho unilateral caneleiras ou maquina', 'Standing_Leg_Curl'),
  ('Glute Ham Raise', 'Natural_Glute_Ham_Raise'),
  ('Good Morning Sentado', 'Seated_Good_Mornings'),
  ('Levantamento Terra Romeno', 'Romanian_Deadlift'),
  ('Mesa Flexora', 'Lying_Leg_Curls'),
  ('Nordic Curl', 'Natural_Glute_Ham_Raise'),
  ('Stiff', 'Stiff-Legged_Barbell_Deadlift'),
  ('Stiff Unilateral', 'Stiff-Legged_Dumbbell_Deadlift'),
  ('Agachamento Sumô com Halter', 'Plie_Dumbbell_Squat'),
  ('Bridge Unilateral', 'Single_Leg_Glute_Bridge'),
  ('Cadeira Abdutora', 'Thigh_Abductor'),
  ('Coice na Polia', 'One-Legged_Cable_Kickback'),
  ('Elevação Pélvica', 'Butt_Lift_Bridge'),
  ('Glute Kickback', 'One-Legged_Cable_Kickback'),
  ('Hip Thrust', 'Barbell_Hip_Thrust'),
  ('Panturrilha Burrinho', 'Donkey_Calf_Raises'),
  ('Panturrilha em Pé', 'Standing_Calf_Raises'),
  ('Panturrilha no Leg Press', 'Calf_Press_On_The_Leg_Press_Machine'),
  ('Panturrilha Sentado', 'Seated_Calf_Raise'),
  ('Panturrilha Unilateral', 'Dumbbell_Seated_One-Leg_Calf_Raise'),
  ('Abdominal Bicicleta', 'Air_Bike'),
  ('Abdominal Crunch', 'Crunches'),
  ('Abdominal na Polia', 'Cable_Crunch'),
  ('Dead Bug', 'Dead_Bug'),
  ('Elevação de Pernas', 'Flat_Bench_Lying_Leg_Raise'),
  ('Hanging Leg Raise', 'Hanging_Leg_Raise'),
  ('Mountain Climber', 'Mountain_Climbers'),
  ('Prancha Abdominal', 'Plank'),
  ('Prancha Lateral', 'Side_Bridge'),
  ('Russian Twist', 'Russian_Twist'),
  ('Wood Chop na Polia', 'Standing_Cable_Wood_Chop'),
  ('Bike Ergométrica', 'Bicycling_Stationary'),
  ('Corrida na Esteira', 'Running_Treadmill'),
  ('Elíptico', 'Elliptical_Trainer'),
  ('Pular Corda', 'Rope_Jumping'),
  ('Remo Ergômetro', 'Rowing_Stationary'),
  ('Sprint', 'Wind_Sprints'),
  ('Stair Master', 'Stairmaster'),
  ('Battle Rope', 'Battling_Ropes'),
  ('Box Jump', 'Front_Box_Jump'),
  ('Clean and Press', 'Clean_and_Press'),
  ('Kettlebell Swing', 'One-Arm_Kettlebell_Swings'),
  ('Sled Push', 'Sled_Push'),
  ('Snatch', 'Snatch'),
  ('Thruster', 'Kettlebell_Thruster'),
  ('Turkish Get-Up', 'Kettlebell_Turkish_Get-Up_Squat_style')
ON CONFLICT (exercise_name_pt) DO UPDATE SET slug = EXCLUDED.slug;

-- Pré-popula image_url nos exercícios públicos que tem mapeamento
UPDATE public.exercises e
SET image_url = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/' || m.slug || '/0.jpg'
FROM public.exercise_image_map m
WHERE e.name = m.exercise_name_pt
  AND e.is_public = true
  AND (e.image_url IS NULL OR e.image_url LIKE '%supabase.co/storage%');